baseURL = "https://www.gwbland.com/"
languageCode = "en-us"
summaryLength = 20
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Buyers"
weight = 2
[[menu.main]]
name = "Resources"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
cloudinary_url = "https://res.cloudinary.com/realestate2/image/upload/"
[taxonomies]
category = "categories"
city = "cities"
featured = "featured"
property = "properties"
state = "states"
status = "status"
tag = "tags"
zip = "zip-codes"
